
const eventType = {
	SYSTEM_ARRIVAL: 'SYSTEM_ARRIVAL',
	SERVICE_START: 'SERVICE_START',
	SERVICE_END: 'SERVICE_END',
	SERVICE_INTERRUPTION: 'SERVICE_INTERRUPTION',
	SERVICE_RESUME: 'SERVICE_RESUME'
};

exports.EventType = eventType;